kortex_hardware/b_0: 0.3
kortex_hardware/b_1: 0.3
kortex_hardware/b_2: 0.3
kortex_hardware/b_3: 0.3
kortex_hardware/b_4: 0.18
kortex_hardware/b_5: 0.18
kortex_hardware/b_6: 0.18
kortex_hardware/d_0: 2.0
kortex_hardware/d_1: 2.0
kortex_hardware/d_2: 2.0
kortex_hardware/d_3: 2.0
kortex_hardware/d_4: 2.0
kortex_hardware/d_5: 2.0
kortex_hardware/d_6: 2.0
kortex_hardware/d_z: 40.0
kortex_hardware/j_0: 4000.0
kortex_hardware/j_1: 4000.0
kortex_hardware/j_2: 4000.0
kortex_hardware/j_3: 4000.0
kortex_hardware/j_4: 3500.0
kortex_hardware/j_5: 3500.0
kortex_hardware/j_6: 3500.0
kortex_hardware/k_0: 50.0
kortex_hardware/k_1: 20.0
kortex_hardware/k_2: 20.0
kortex_hardware/k_3: 20.0
kortex_hardware/k_4: 10.0
kortex_hardware/k_5: 10.0
kortex_hardware/k_6: 10.0
kortex_hardware/l_0: 75.0
kortex_hardware/l_1: 75.0
kortex_hardware/l_2: 75.0
kortex_hardware/l_3: 75.0
kortex_hardware/l_4: 40.0
kortex_hardware/l_5: 40.0
kortex_hardware/l_6: 40.0
kortex_hardware/lp_0: 5.0
kortex_hardware/lp_1: 5.0
kortex_hardware/lp_2: 5.0
kortex_hardware/lp_3: 5.0
kortex_hardware/lp_4: 4.0
kortex_hardware/lp_5: 4.0
kortex_hardware/lp_6: 4.0
